### ISSUE TITLE
Can you filter out what is showing up?

### ISSUE THREAD

**Issue by heartfrappe** [AHAAAAAAA/PokemonGo-Map#1117]
I'm a new user. Rather n00b at Python too.

I got the app to work on my machine, but I was wondering if there is a way to rule out certain pokemon or even search specifically for one, no matter where it shows up?

For example, can I load a variable to locate only Charmanders?

Also, can I rule out the Pidgeys and Rattatas?

P.S. GREAT WORK to all the devs! This is outstanding and easy to use!

**Comment by Nicknack1234** [comment]
`-h Show Help`
In Help:
` -i IGNORE, --ignore IGNORE
                       Comma-separated list of Pokemon names or IDs to
                       ignore
 -o ONLY, --only ONLY  Comma-separated list of Pokemon names or IDs to
                       search`

**Comment by heartfrappe** [comment]
Great help! I didn't know I could get a help menu... Thanks for sharing!

**Comment by Whoknowsit** [comment]
Too bad, these options have been removed in the current development branch.

**Comment by heartfrappe** [comment]
It's too bad there isn't a way to do a mass query to cover an entire zip code and filter out only the one I want... oh well.. it helped my wife and kids get a ponyta today... so it was well worth the effort to get it stood up.

**Comment by Whoknowsit** [comment]
The current development branch has a "live filter" in the UI that makes filtering a little bit easier.

**Comment by heartfrappe** [comment]
Well that's awesome. How easy is it to update to the new branch when it is released as master?

**Comment by Nordsted** [comment]
Whoknowsit that sounds nice! I was just about to ask if it would be possible to do such a thing :)!

Also a filter could be minimumClusters so you only want to see clusters of minimum X amount of pokemons. It's just not always fun to scout the map for single pokemons if you can have shown the places where you catch a lot :-) I think cluster within 100 meter or so

**Comment by Whoknowsit** [comment]
You should go and try the development version and create a new issue/suggestion then. Otherwise, it might stay unseen :)

**Comment by Nordsted** [comment]
I will do that :D Was just about to write another thing :P

**Comment by neobithia** [comment]
Thanks for updating the app with the Live Filter feature, but it's not easier to use than what we had before.  It's so tedious to have to scroll through the dropdown list and find the Pokemon you want to filter out.  What's worse is that they aren't in alphabetical order.

Would it be possible to just use a textfield where we can paste in Pokemon names separated by a comma?  That would be so much faster to use.

Another option is to make the filter into a button that activates a layer that looks like the Pokemon List activity in the app.  Since all we already have all of the Pokemon icons, we can just arrange them into a grid like in the app, except in alphabetical order so it's easier to find.  Then, the user just touches each icon to toggle "hide/show" Pokemon.  Then, they just scroll through and touch all the ones they want to show or hide.  Then, the close the layer and it saves the preferences persistently across sessions.

**Comment by MonkeyLeeT** [comment]
Closing this issue as it is outdated. If this issue still persists on the `develop` branch, please reopen a new issue and update the information therein to reflect the new changes.
