### ISSUE TITLE
Google maps unable to load correctly in DEV only. 

### ISSUE THREAD

**Issue by Secret0tter** [AHAAAAAAA/PokemonGo-Map#1332]
"Google maps did not load correctly. See the Javascript console for more details." Error i'm getting when loading localhost:5000. I'm a noob so I have no idea what to do.

**Comment by Faustvii** [comment]
This will most likely resolve your issue.
https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Google-Maps-API:-a-brief-guide-to-your-own-key

**Comment by Frozire** [comment]
Start by opening the console for more details.

How to open the JavaScript console in different browsers.
http://webmasters.stackexchange.com/posts/77337/
__________________________________________________________

# Chrome

Opening the “Console” panel of Chrome’s **DevTools**:

 - Windows: <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>J</kbd>

 - Mac OS: <kbd>Cmd</kbd> + <kbd>Opt</kbd> + <kbd>J</kbd>

*Note: In addition to the “Console” panel, there also exists a smaller slide-up console which can be toggled via <kbd>Esc</kbd> while any of the other panels is active.* 

[Full documentation](https://developer.chrome.com/devtools/docs/shortcuts)

---

# Firefox

Opening the “Console” panel in Firefox’s **Developer Tools**:

 - Windows: <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>K</kbd>

 - Mac OS: <kbd>Cmd</kbd> + <kbd>Opt</kbd> + <kbd>K</kbd>

*Note: In addition to the “Console” panel, there also exists a smaller slide-up console which can be toggled via <kbd>Esc</kbd> while any of the other panels is active.* 

[Full documentation](https://developer.mozilla.org/en-US/docs/Tools/Keyboard_shortcuts)

---

# Internet Explorer 

Opening the “Console” panel in Internet Explorer’s **F12 Developer Tools**:

 - <kbd>F12</kbd>, then click on the “Console” tab

*Note: In addition to the “Console” panel, there also exists a smaller slide-up console which can be toggled via <kbd>Ctrl</kbd> + <kbd>`</kbd> while any of the other panels is active.* 

[Full documentation](https://msdn.microsoft.com/en-us/library/ie/dn322041%28v=vs.85%29.aspx)

---

# Safari

*Note: In order to view the console in Safari, you have to enable the “Show Develop menu in menu bar” setting in the “Advanced” pane of Safari’s preferences ([screenshot](https://developer.apple.com/library/mac/documentation/AppleApplications/Conceptual/Safari_Developer_Guide/GettingStarted/GettingStarted.html)).* 

Opening the “Console” panel in Safari’s **Web Inspector**:

 - <kbd>Cmd</kbd> + <kbd>Opt</kbd> + <kbd>C</kbd>

*Note: In addition to the “Console” panel, there also exists a smaller slide-up console which can be toggled via <kbd>Esc</kbd> while any of the other panels is active.* 

[Full documentation](https://developer.apple.com/library/mac/documentation/AppleApplications/Conceptual/Safari_Developer_Guide/KeyboardShortcuts/KeyboardShortcuts.html)

**Comment by Secret0tter** [comment]
@Faustvii that fixed it. I had done that previously but I guess I fucked up somewhere along the way :P. Well it's working now so coolio. Thank you guys for all your work on this I know me and many others greatly appreciate it! :)

**Comment by Faustvii** [comment]
That's great. Remember to close the issue.
