### ISSUE TITLE
Cannot start runserver.py

### ISSUE THREAD

**Issue by ChristianLuxem** [AHAAAAAAA/PokemonGo-Map#1392]
## Expected Behavior
Start the Map....

## Current Behavior
C:\Users\chris\Documents\Pokemon Go\PokemonGo-Map-develop>python runserver.py
Traceback (most recent call last):
  File "runserver.py", line 12, in <module>
    from pogom import config
ImportError: cannot import name config

## Steps to Reproduce (for bugs)

1. Download current Repo
2. fill out the config.ini 
3.try to start
4.

## Context

I am wondering, where the documentation is, about how to use the config.ini and the other arguments? There is a link to the documentation from the master-branch in the readme-file... That does not help. 

## Your Environment

* Version used: latest
* Environment name and version (e.g. Python 2.7): 2,7
* Operating System and version (desktop or mobile): Windows 10

**Comment by Unsworth94** [comment]
Please see the [Wiki](https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Usage) to see the parameters you need to pass along with this command :)

**Comment by ChristianLuxem** [comment]
Thanks for the link to the wiki, but there is no documentation how to use the config.ini and also if i try your example, it fails with the same error.

**Comment by ApocUSB190** [comment]
If you want to use the config.ini file, you must pass the -se argument to runserver.py.  Otherwise, it will continue to look for arguments in the command line.

Alternatively, since the config.ini is buggy right now, you can just make a batch file as I have done to store your information.

Steps:
1. Open notepad.
2. Paste in whatever you would like run.  Example from my batch file: python runserver.py -a google -u YOURUSERNAMEHERE -p YOURPASSWORDHERE -l "LOCATION" -st 10
3. File -> Save as...
4. At the bottom where it says "Save as type: " change from text documents to all files.
5. Name it whatever you want, and append .bat to the end.  Example: run_server.bat
6. Save this file to the same directory as runserver.py.
7. Double click it and your server should begin to run.

**Comment by SimpleCookie** [comment]
I'm experiencing the exact same problem and I haven't found any solution either. It seems rather illogical to me.

**Comment by ChristianLuxem** [comment]
It was fixed with a newer version. I will close this.
