### ISSUE TITLE
Percent Scanned Dosn't Reset

### ISSUE THREAD

**Issue by arianizadi** [AHAAAAAAA/PokemonGo-Map#1413]
When the Scan reaches 100% is continues to 101 and so on.

**Comment by Valareos** [comment]
@arianizadi they switched from a rectangular scan pattern to a hexagonal scan pattern (which works better for circular scans which the pokemon go uses). So number of steps increased. (instead of 100 scans for 10 steps, it is 271 to cover a hex pattern)  You end up with a more exact "radius" around yourself.

The bug that exists is the number of total steps they use for the % calculation is still based on rectangular steps

**Comment by arianizadi** [comment]
@Valareos Alright thanks

**Comment by chuyskywalker** [comment]
Scan % was removed.
