### ISSUE TITLE
google 2step auth and cant log in

### ISSUE THREAD

**Issue by thu2468** [AHAAAAAAA/PokemonGo-Map#144]
add google 2step auth. also when i try to log in it say unknown user/password even though it is correct

**Comment by olipayne** [comment]
See [here](https://support.google.com/accounts/answer/185833)

**Comment by SmithsonianDSP** [comment]
yep, @olipayne is correct. You need to [create an app password](https://security.google.com/settings/security/apppasswords) (go to the bottom, click the select app dropdown, choose other, type in whatever name you want to remember it with, then use the password it shows you afterwards to sign in. 

Remember to write down or save the password somewhere, though, because you won't be able to look at it again later; if you forget it, you'll have to generate a new app password.
