### ISSUE TITLE
Package up a release for end users

### ISSUE THREAD

**Issue by BillyWM** [AHAAAAAAA/PokemonGo-Map#1604]
There should be a release for non-dev end users, and anyone who isn't interested in debugging or submitting patches should be pointed there.

End users should not be in develop at all.

https://help.github.com/articles/creating-releases/
https://github.com/AHAAAAAAA/PokemonGo-Map/releases

**Comment by coolaj86** [comment]
How should we go about this?

What level of end-user? Like my mom who gives up if click the easy button fails (innosetup exe, pkg, deb, etc)? Or my sister who can google if she's really motivated (zip with a clickable run.bash inside)? Or someone who is pretty IT/CS-savvy?

Concerns:

* Users must get Google Maps API key
* Users must install python
* Users must open a commandline to run the python from the directory
* Users must specify many options via commandline or config file

I'd suggest moving the all of the config (username, password, location, gmap_key, steps) to the web client and then make it so it can run from a zip file, listening on 0.0.0.0 rather than 127.0.0.1 (so that it'll "just work".

**Comment by BillyWM** [comment]
Yes, it's hard to run. This is simply a suggestion to branch off a stable release, where all the common difficulties are known. Having non-devs run develop, where code changes many times per day, just multiplies the complexity.

--------------------

>What level of end-user? Like my mom who gives up if click the easy button fails (innosetup exe, pkg, deb, etc)? Or my sister who can google if she's really motivated (zip with a clickable run.bash inside)? Or someone who is pretty IT/CS-savvy?

Concerns 2, 3, and 4: It's built on Python so it's going to be hard to get running. Python has never been friendly for your mom to run but your sister probably could. Your mom should probably try https://github.com/mchristopher/PokemonGo-DesktopMap

Concern 1: No way around the API key. It's built on Google Maps and that's their rule.

**Comment by coolaj86** [comment]
I put together a package for my node server + this web client: https://github.com/Daplie/node-pokemap (positioning is currently manual, so you only see immediately nearby Pokémon, but I plan to fix that Monday)

I haven't tested it on windows, but I think that both node.js and python rely on the C s2-geometry library bindings, which is a point of annoyance (my package probably only runs on Mac at the moment due to this).

**Comment by BillyWM** [comment]
Releases have been created. Cool! Closing this.
