### ISSUE TITLE
Config.ini Still useless?

### ISSUE THREAD

**Issue by keaza** [AHAAAAAAA/PokemonGo-Map#1613]
Am i the only one here, or am i just being plain dumb. the config file  in ../config/config.ini is there so we shouldnt have to enter passwords in plaintext (surely?) i run my map server on a shared machine in linux so my password is left in plain text in my .bash_history.

Anyone want to give me a pointer to what im doing wrong?

**Comment by mattb91** [comment]
if you run with the -se flag it will use config.ini

**Comment by Zentriert** [comment]
Has the command changed? I get " runserver.py: error: unrecognized arguments: -se " when I try "python runserver.py -se"

**Comment by andrewda** [comment]
The config is used by default now. The `-se` argument no longer exists.

**Comment by Zentriert** [comment]
... I knew it was something like that and it's really aggravating because I spent over an hour searching the issues/commits with different terms and found nothing but other people with similar problems due to lack of documentation. 

I understand this is very new and changing a lot, but this is not the first time I've had to post in a developer section just to figure out very simple things that should have been commented in the config.ini
