### ISSUE TITLE
How to run high number of instances without problem?

### ISSUE THREAD

**Issue by gosp07** [AHAAAAAAA/PokemonGo-Map#1968]
I can run around 4 -5 without any big errors but when I go over 10 I started to get database errors. even if I seperate bots in different files I still get error because they both use python scripts I think. I'm no expert so I cant say anythin certain. Is there anyway to run over 10 instances without having problems? They dont need to dump on same db they can be seperated.

**Comment by Shiryu75** [comment]
I recommend you to start using MySQL instead of SQLite datatable.
For that, use branch develop and edit the file config/config.ini (rename it from example if necessary).

Also, you'll have to make some modifications. 
- You will have to add parameter "-se" when starting runserver.py, to load the config.
- You will also have to edit pogom/utils.py to comment at least 2 lines: 
               #args.location = Config.get('Search_Settings', 'Location')
               #args.port = Config.get('Misc', 'Port')

For the matter, I only added the # before so the line is ignored.

Why ? Because if you load the config (-se) without commenting those lines, you won't be able to start multiple instances from different locations and port. 

So by commenting that, you will be able to ignore location and port from config.ini. You'll just have to add those parameters in the command line as before, with -l and -P, for each instance.

Of course you can comment other lines if you want depending on how you want to position your instances.

Remember that you might have to do it again in the future for every git pull you make.

Hope it would help.

cya

**Comment by gosp07** [comment]
![asd](https://cloud.githubusercontent.com/assets/20618367/17099379/994889bc-5270-11e6-802d-2d7e3db678d6.png)
I get this error . I did everything on the wiki page

**Comment by Shiryu75** [comment]
the last line sayd "unknown database". Please review the name you gave to the database.

**Comment by medghaim** [comment]
https://discord.gg/Kamn6
