### ISSUE TITLE
Scan locations far from the center are increasingly off

### ISSUE THREAD

**Issue by sgitkene** [AHAAAAAAA/PokemonGo-Map#2187]
Close to the center the circles of scanned locations align and cover all the ground. But further outside (I tried it with -st 100 and waited 20 minutes) you will get this picture:

![screenshot from 2016-07-26 14-42-44](https://cloud.githubusercontent.com/assets/11799843/17138279/ca4dbb5c-533f-11e6-94a5-d0c69f0ba523.png)

This is likely a small error that gets added again and again.

**Comment by hgentry** [comment]
Some of us were just talking about this in chat and I think I'll just paste what I said there:

**hgentry - Today at 9:17 AM**
I think the best way to reduce these errors is to limit the number of floating point operations needed to reach any given point
it would increase total calculations by a complexity factor of log n, but the optimal reduction of flops per scan (thus minimizing error) is by a tree of log n height where n is the number of scans
where each node in the tree is another tier of beehive, i e we first pick a single point on the Earth. Then we use that to pick a small number of points on other ends of the globe, maybe 6-8 total
that would basically divide the globe into segments defined by which of these points is closest
and then you use those points to generate the same number of points evenly spread in their segment
and keep iterating until you're down to the individual scan level
the complexity becomes f(nlogn) instead of f(n) but coverage would be maximized
#complexitytheory
(I graduated four years ago and this is the first time I've really felt like I was putting my math degree and graduate theory courses to good use)

**Comment by omenius** [comment]
I reported this bug also earlier, I think nobody noticed. For my use case, this is very bad behavior. I'm mostly trying to use the scan results for statistics and if the map is not scanned uniformly, the results are bad. Of course you could calculate weights for every area, that tells how "well" scanned any given area is, but I don't have  time to implement anything like that.

**Comment by medghaim** [comment]
I should have a fix for this!

**Comment by medghaim** [comment]
Testing fix, looking good.
