### ISSUE TITLE
Auto-refresh on by default: yay or nay?

### ISSUE THREAD

**Issue by AHAAAAAAA** [AHAAAAAAA/PokemonGo-Map#225]
I think it's great and works great. I think it should be the default setting. Counter points?

**Comment by thefeeltrain** [comment]
Yay

**Comment by michi0987** [comment]
VoteYea

**Comment by Skullmonkey** [comment]
Yay, but I would like to not see 

> 127.0.0.1 - - [18/Jul/2016 21:05:57] "GET /data HTTP/1.1" 200 -
> 127.0.0.1 - - [18/Jul/2016 21:06:00] "GET /data HTTP/1.1" 200 -
> ...

In the command window if possible.

**Comment by nborrmann** [comment]
Yes it's great and should be on by default, but theres three issues with it currently:

1. after loading the icons briefly appear but then disappear until the next reload
2. icons always flash when reloading
3. expired pokemon stay on the map for too long. this is because the old ones will only be removed when the next scan begins. maybe we should call `clear_stale_pokemons()` in the controller?

**Comment by JZ6** [comment]
yay , i use -ar 3 on mine

**Comment by hhu94** [comment]
Yay, but I think we should fix the issue with the markers being not clickable first.

**Comment by XoneFobic** [comment]
at `-ar 5` this still seems to be the issue right after an actual refresh
https://dl.dropboxusercontent.com/s/hv1c1x69j882f1z/DB71365C-A858-4AB8-9206-A8213749F080-22366-0001132B35683DBF.gif?dl=0

**Comment by JZ6** [comment]
but why would you refresh when auto refresh is there

**Comment by XoneFobic** [comment]
@JZ6, it happens on page load. Not only on refresh.

**Comment by JZ6** [comment]
ah i see ya i get the split second of blank map as well

**Comment by getreadysetgo** [comment]
One big downside of autorefresh is that if the user wants to zoom in (me, everytime), the refresh will wipe that out every few seconds.

Rather than autorefresh, each time a step completes, you could plot the markers iteratively.

Based on their earlier PR, I bet @nborrmann could handle this without too much work. (I'm thinking [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events) for keeping the data fresh between and and front is probably the least stressful.

**Comment by nborrmann** [comment]
@getreadysetgo that's already in there. courtesy of foodforarabbit

**Comment by vintagesucks** [comment]
Possible downside could be data usage on mobile. If this get's enabled by default I'd like to see something like `-ar false`

**Comment by XoneFobic** [comment]
@vintagesucks, maybe browser parameters `?at=10`, or something like it

**Comment by hgentry** [comment]
#223 looks like the best option to me, too. Not having random flashes is always a plus.

**Comment by rochacbruno** [comment]
#223 looks the best option, reuse the existing não, so no flashes and markers can be updated/created interactively keeping the user zoom.

**Comment by sandsaber** [comment]
+
