### ISSUE TITLE
Feature Request: 'Scanned Location' Circles QoL

### ISSUE THREAD

**Issue by Forza4Development** [AHAAAAAAA/PokemonGo-Map#2318]
## Expected Behavior
The most recent scanned areas should be a Light Blue, to indicate that these areas are the most recently scanned areas.  Once new areas are scanned, they will default back to green, indicating that they were scanned recently.

## Current Behavior
After the scan completes its first iteration, we are unable to detect where it has most recently scanned.

**Comment by Sunakujira1** [comment]
By "most recent scanned areas", do you mean the modified/updated scanned areas since last call/render?

**Comment by Forza4Development** [comment]
@Sunakujira1 Yes.  That is what I meant.

**Comment by Sunakujira1** [comment]
This sounds like it'll add quite some complexity for not much gain. If your map is getting updated too fast hence it's always green, perhaps you can modify [develop/static/map.js#L602](https://github.com/AHAAAAAAA/PokemonGo-Map/blob/develop/static/map.js#L602)'s `/ 15` value to something lower, so that color changes more drastically and will be more noticeable?

**Comment by Forza4Development** [comment]
That seems like a better solution.  I will try this.  Thanks for the tip!
