### ISSUE TITLE
[QUESTION] -TD and -SD

### ISSUE THREAD

**Issue by daproject85** [AHAAAAAAA/PokemonGo-Map#2391]
can someone please explain the mechanics of -TD and -SD. If i am running a step of 8, and 3 threds, how would diff values for -TD and -SD impact things..

sorry posting this here, people discord are of no help

**Comment by Birkbjo** [comment]
Well, since commit 8fc0a66fbe6c8f16d059db5ccf8763b78b9b6a64, -td is basically the wait time between a scan is complete and a new search at the location is started. 
So after your 3 threads have completed your search it will wait i.e 5 seconds before a new search is stared. 
Remember, a complete search/scan are a collection of multiple locations to request and parse.

-sd is the time between each threads are sending requests (to fetch a new location), so after it recieves and parses a location, it waits -sd seconds before requesting and parsing the next location. 

So generally -td can be higher.
A high -sd will make your scan slower - but more pressure on Niantics servers, and we do not want that, right? :)
