### ISSUE TITLE
Notification of pokemon (when using --only)

### ISSUE THREAD

**Issue by Krys1s** [AHAAAAAAA/PokemonGo-Map#244]
You guys have been killing it with this project.

For super lazy people like myself, it would be great for the browser to kick off some sort of notice when a pokemon matching the -o/--only filter pops.

Would allow it to be run fully in the background scanning for specific rares. 

- Popup notice
- Audio ping
- Red dot on browser tab
etc

**Comment by Darkrift411** [comment]
I would like this option even with the -i flag. I have something like 75 on my ignore list so I do not feel it would get too annoying too fast. What if the sound on/off was a checkbox or button you could press in the browser (speaker icon)? If enabled in config/command line, you have the icon and can use that to mute it (per user) instead of server-side. I guess while adding this a tab title update could be done via JS.

**Comment by FlyVik** [comment]
Hello! I'm from Ukraine. interested in playing Pokemon go read this article https://github.com/AHAAAAAAA/PokemonGo-Map, and I can not ask, I do not understand, could not you help me?

**Comment by KevakaBuel** [comment]
Would definitely like such a feature. Just run an instacne with only very rare pokemon and get a notification when something is nearby would be priceless. Dont know how much work it is and if it can work without hosting the whole script.

**Comment by tj-corrigan** [comment]
To push this a bit further it would be great to see some sort of webhook support to integrate with other services (thinking Slack as an example).

**Comment by Krys1s** [comment]
https://www.reddit.com/r/TheSilphRoad/comments/4tsrjc/i_made_a_slack_bot_to_track_the_pok%C3%A9mon_spawns_in/

Would be awesome =)
