### ISSUE TITLE
How can we run multiple agents with single config file?

### ISSUE THREAD

**Issue by MonsterMMORPG** [AHAAAAAAA/PokemonGo-Map#2457]
How can we run multiple agents with single config file?

I want each agent to scan different area

**Comment by F10XDE** [comment]
i assume you want to do this automatically? otherwise you can change the location using the web tool.

If you're running from cmd you can batch up multiple versions of the same run script with different locations. You can then run all and it will scan multiple areas. But once the first one comes back round to step 1 it will lock the db, stopping the other instance writing to the file, meaning you need to rinse and repeat manually.

**Comment by MonsterMMORPG** [comment]
@F10XDE  ty so i guess not possible

I wish we could define a separate account for each thread

So lets say i define 4 accounts and 4 thread count so each thread get 1 account but no problem
