### ISSUE TITLE
Multiworkers (question)

### ISSUE THREAD

**Issue by Antitankers** [AHAAAAAAA/PokemonGo-Map#2489]
I can't see to find anything on it so I just have to ask where do I put my extra worker logins as the config.ini file only has one username and password line ?
I assume threads(in the config.ini) would be set to the amount of workers you have running then

**Comment by SpeckledTrout** [comment]
You're looking for an account pool. As it is there is no account pool functionality. Multi thread is not multi workers though, threads share an account. 

Beehive is more like multi workers and alas they all use the same config.ini as it is. There'd be no good way to distribute the pool though  because they are independent processes. If you want multiple accounts pass them on the command line to each worker.

**Comment by hgentry** [comment]
You don't need to change anything in the config to use workers. When you start up a worker, you usually run:

`python runserver.py -ns -l "location"`

For each worker, instead do

`python runserver.py -ns -l "location" -u USERNAME -p PASSWORD -a GOOGLE_OR_PTC`

and put your username, password, and authenticator in place of those all-caps.

**Comment by wcastello** [comment]
Threads just divide the amount of work of a single login, if you want to run multiple logins you have to run multiple processes. Leave the common stuff on config.ini and use -u and -p.
https://discordapp.com/channels/204338767920758785/204339169458126849
https://github.com/AHAAAAAAA/PokemonGo-Map/wiki

**Comment by jforr** [comment]
Is there a reason for running multiple accounts other than obfuscating the fact that you're running a bot?

**Comment by hgentry** [comment]
Not that I'm aware of
