### ISSUE TITLE
 [runserver] [CRITICAL] Please run "grunt build" before starting the server.

### ISSUE THREAD

**Issue by Schwaitz** [AHAAAAAAA/PokemonGo-Map#2581]
Hello!

Just pulled the latest version from the dev branch and ran into two problems. Firstly, the pip package LatLon was unable to be installed due to a LONG string of errors.

Secondly, I got the error from the title. Here is the command I tried to run:

`sudo python2.7 runserver.py -a ptc -u CENSORED -p hunter2 -l "xxx, -xxx" -st 8 -sd 1 -H 0.0.0.0 -P 5000 -t 20 -C -D justin.db`

And the error that I recieved:

`[runserver] [CRITICAL] Please run "grunt build" before starting the server.`

Are the two errors related? What is the LatLon package? It seems to fail on something called PyProj, and not actually LatLon?

Thanks!

**Comment by clarkjam** [comment]
I am also seeing this problem. Have been downloading zips and running the develop branch without issue until this commit.

**Comment by buddytohelpu** [comment]
Same issue for me.

**Comment by Coffee4cr** [comment]
Same issue here, and if I run grunt build, it doesn't help.

**Comment by am93** [comment]
Same issue here, when deploying to Heroku (deployed cca 30 mins ago)

**Comment by rlex** [comment]
it's not an issue. Developers switched to building static files with grunt. 
I installed nodejs 4.x, ran npm install in root of PokemonGo-Map, and executed grunt build after that.
Works good.

**Comment by Sp0one** [comment]
How do I fix this for Heroku deployment ?

**Comment by Schwaitz** [comment]
@rlex It sort of is a problem, because I use the pure runserver.py.

**Comment by Widoww** [comment]
Also seeing this with latest build deployed to heroku

**Comment by BallCity** [comment]
You have to revert the latest two commits related to GRUNT manually. Then it will deploy and run fine.

**Comment by buddytohelpu** [comment]
How do we run grunt build? I did the npm install, not sure where to go next.

**Comment by MRokas** [comment]
Install node.js + npm

Run `npm install`
Run `grunt`

After that you can start server.

**Comment by wschoot** [comment]
I think, running CentOS 6, I need a newer node (from https://nodejs.org/en/download/package-manager/#enterprise-linux-and-fedora) as my OS ships with 0.10.

**Comment by smalldragor** [comment]
How do you run grunt on windows ?

**Comment by Gamewalker** [comment]
U install NodeJS https://nodejs.org/en/ on windows and run from CMD

npm install
grunt build

in your main directory of pokemon-map

**Comment by buddytohelpu** [comment]
when I type grunt build it says "grunt" is not a recognized as internal or external command. Where would the path be for grunt that way I can do "c:/path/grunt build"

**Comment by Gamewalker** [comment]
try
npm install -g grunt-cli
before

**Comment by brantwynn** [comment]
According to the package.json, grunt build should be run during deploy. So I am not sure why the error persists. For now, I am just removing the check (comment out lines 33-35 on runserver.py) because either a) grunt build is not actually running or b) the check doesn't work correctly.

`"scripts": {
    "postinstall": "./node_modules/.bin/grunt build",
    "build": "./node_modules/.bin/grunt build",
    "lint": "./node_modules/.bin/grunt lint"
  },`

**Comment by DACRepair** [comment]
so what I found needed to be done was this:
I dug and found that even though the `npm install` worked, the post build did not:
`npm WARN cannot run in wd...........`

try rerunning `npm install` with the `--unsafe-perm` argument, this fixed it for me.

`npm install --unsafe-perm`

**Comment by BallCity** [comment]
For those on HEROKU, it's actually really simple. You just have to add the "heroku/nodejs" buildpack to your app. You can do this from the web GUI under "Settings" (https://dashboard.heroku.com/apps/<your-app>/settings).

Scroll down to "Buildpacks" click "Add buildpack" select "Nodejs", save changes, then re-deploy your app. It should then download/install all the stuff you need automatically.

**Comment by marauder37** [comment]
Heroku people, I accepted a PR that was meant to fix this, is it still busted on the very latest develop?

**Comment by Znuff** [comment]
Just unzip this file (dist.zip) into the "static" directory. You're done.

[dist.zip](https://github.com/AHAAAAAAA/PokemonGo-Map/files/390756/dist.zip)

**Comment by Sebkasanzew** [comment]
@marauder37 adding nodejs as a buildpack in the heroku dashboard, as @BallCity suggested, solved it for me.

**Comment by Ketakku** [comment]
I am having some issues getting grunt installed. I am running an ubuntu server. Any help would be appreciated.

**Comment by MRokas** [comment]
@Ketakku 

Install node.js + npm
then do this: `sudo install --global grunt grunt-cli`
after that using `grunt` should be ok.

**Comment by HinoReo** [comment]
This is THE solution https://github.com/AHAAAAAAA/PokemonGo-Map/issues/2581#issuecomment-236198411
@Znuff Thank you!

**Comment by AHAAAAAAA** [comment]
Please understand that develop is not release. Develop is not release. Develop is not release. If you want a 2 command run, stick to release. We're using grunt in an attempt to improve code health, and sorry that's not going to be changed. If you're able to install everything on develop and run it by yourself, that's great but we will not be solving any issues or hand-holding anyone through this. It's a development branch, for development. This isn't for the end user, it's for us working on building this project out.

**Comment by brantwynn** [comment]
@AHAAAAAAA totally get where you're coming from but I think the reason a lot of people end up on develop is because of the docs.  https://github.com/AHAAAAAAA/PokemonGo-Map/wiki#project-refactor

**Comment by sebastienvercammen** [comment]
@AHAAAAAAA @brantwynn The error returned by runserver.py (please run grunt build) is also not at fault: it, by itself, doesn't set the requirement for grunt. Rather than displaying "You're missing the dist files" (which not a single end user will understand & link to grunt), it correctly mentions the steps that should have been run during installation.

(Again, whether the grunt requirement is a good or a bad thing is another discussion. I'm also not a big fan of all the requirements.)

However, the decision to remove the dist files was a good one. Having them on the repo means every single line that is changed in the source files results in an entirely new compressed file, creating massive overhead on the repo.

And while I understand @Znuff his intentions for distributing the files in a zip, I would recommend against it. It might help not having to install all the requirements for more technical users (big yay), but the non-technical people trying to install the map have already started joining #help on Discord saying they have a blank map: turns out they didn't feel like installing grunt or running grunt build so they downloaded the zip, but they unzipped it to the wrong folder.

While grunt comes with large extra requirements (that, imo, should have never been put in in the first place), it also prevents [PEBKAC](https://en.wikipedia.org/wiki/User_error), which is important when dealing with public projects.

**Comment by danielediazmx** [comment]
try using:

./node_modules/.bin/grunt build

tested on mac os x.
