### ISSUE TITLE
Unable to run server

### ISSUE THREAD

**Issue by GibbyOH** [AHAAAAAAA/PokemonGo-Map#2700]
I just downloaded the new server dev package ran pip install -r requirements.txt and got the following error 

Command "python setup.py egg_info" failed with error code 1 in c:\users\josh~1.a
dm\appdata\local\temp\pip-build-gnlblv\pyproj\

now when I try to run the server I get either 

runserver.py: error: Unexpected line 4 in C:\PokemonGo-Map-dev\pogom\../config/c
onfig.ini: Service:

or if I fillout the config ini it get 

runserver.py: error: unrecognized arguments: --Service ptc --Username [username]
--Password [password] --Type mysql --Database_Name pokemongomapdb --Database_User
root --Database_Pass [password] --Database_Host 127.0.0.1 --Steps 5 --Location san
dusky, OH --Scan_delay 1 --disable_pokemon false --disable_pokestops false --dis
able_gyms false --Google_Maps_API_Key [gmap_key] --Host 192.168.79.12 --Port 5000

I have gone over the wiki about a dozen times now and still don't have an answer.

I can roll back to the older version and have no issue but as soon as I upgrade again I get the same error when running the PIP install -r requirements.txt and the samething happens.

**Comment by fireXtract** [comment]
I had the same issue until I installed this [https://www.microsoft.com/en-us/download/confirmation.aspx?id=44266](Microsoft Visual C++ Compiler for Python 2.7) but after I installed that I still get errors trying to run npm install and grunt build. Win10 most recent build of dev.
`G:\MAP20160730>npm install
/
> pogomap@0.1.0 postinstall G:\MAP20160730
> grunt build

Loading "uglify.js" tasks...ERROR
>> Error: Cannot find module 'pako/lib/zlib/messages'
Loading "watch.js" tasks...ERROR
>> Error: Cannot find module 'websocket-extensions'
Loading "sass.js" tasks...ERROR
>> Error: ENOENT: no such file or directory, scandir 'G:\MAP20160730\node_modules\grunt-sass\node_modules\node-sass\vendor'
Loading "cssmin.js" tasks...ERROR
>> Error: Cannot find module './source-map/source-map-generator'
Loading "babel.js" tasks...ERROR
>> Error: Cannot find module 'babel-runtime/helpers/typeof'

Running "clean:build" (clean) task
>> 0 paths cleaned.
Warning: Task "babel" not found. Use --force to continue.

Aborted due to warnings.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! pogomap@0.1.0 postinstall: `grunt build`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the pogomap@0.1.0 postinstall script 'grunt build'.
npm ERR! This is most likely a problem with the pogomap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pogomap
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls pogomap
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     G:\MAP20160730\npm-debug.log`

**Comment by invisiblek** [comment]
check out config.ini.example, it looks like you're using the old config options (they are now all lowercase, these are case-sensitive)

**Comment by andrewda** [comment]
As @invisiblek said, the parameters are case-sensitive.
