### ISSUE TITLE
Retire github wiki -- or don't

### ISSUE THREAD

**Issue by chuyskywalker** [AHAAAAAAA/PokemonGo-Map#2701]
https://github.com/AHAAAAAAA/PokemonGo-Map/wiki

https://www.jonaharagon.com/PoGoMapWiki/#!index.md

Pick one, don't care which, but stick to it and kill the other.

**Comment by andrewda** [comment]
Ehh, I like the easiness of GitHub wiki editing without constant pull requests to a gh-page branch on a repository, but the style of https://www.jonaharagon.com/PoGoMapWiki/#!index.md is nice.

**Comment by Axeia** [comment]
I was wondering about that, is this JonaHaragon wiki even set up by one of the developers or is it just to rake in traffic? I have editted the github wiki to include some openSUSE specific steps and made a footnote to run the startup command with '-t 1' if not all pokemon are showing up. I couldn't be bothered to sign up for an account elsewhere and make the same changes again on a second site.

**Comment by chuyskywalker** [comment]
I'd actually really prefer if the documentation was in a directory of _this_ repo so that as PR's are made with functional updates, the documentation goes hand-in-hand.

**Comment by TJohnson93** [comment]
Agree with @chuyskywalker and @Axeia I tend to use the Github Wiki more than the JonaHaragon one... It's just easier to stay within the Github repo...

**Comment by chuyskywalker** [comment]
@JonahAragon what do you think about all this? Could we somehow leverage the markdown you've already created/cleaned up and get it into this repo and, somehow, hook it up to the gh-pages area over here?

**Comment by JonahAragon** [comment]
> is this JonaHaragon wiki even set up by one of the developers

@Axeia If you believe [the Discord tags](https://i.imgur.com/FX4KVPE.png) then yes? 

@chuyskywalker The Markdown for the wiki I'm hosting is at https://github.com/JonahAragon/PoGoMapWiki so theoretically you could just add them back into this wiki, you'd just need to change some internal links to get everything working. My impression from JZ6 when [it](https://github.com/JonahAragon/PoGoMapWiki) was made was that we'd just be switching to the one I was hosting because of the aesthetics and the Pull Requests system on a dedicated repo (because the system with the GH wiki on this repo is just anybody can edit which imo lacked quality of content and seemed like something that could be modified way too easily), and *then* we'd be shutting this one down/removing everything and adding a "Moved To" notice. *But* nobody really ended up wanting to close this wiki I guess (??) so now they kinda both exist in some weird limbo I don't really understand.

Either way I suppose works.

> I'd actually really prefer if the documentation was in a directory of this repo so that as PR's are made with functional updates, the documentation goes hand-in-hand.

This is another solution to the problem I was attempting to fix, because that way documentation would still have to be approved by devs/moderators. But there's no easy way to integrate a directory in this project either with GH's built in wikis *or* my gh-pages wiki setup, so while it makes things nice and together it decreases user readability.

**Comment by chuyskywalker** [comment]
Perhaps http://read-the-docs.readthedocs.io/en/latest/getting_started.html is in order -- seems like a nice way to handle this. Integrates directly into this repo as a subdirectory, webhooks to build, versioning of the docs, statically build/fast pages.

**Comment by JonahAragon** [comment]
However, that requires a webserver to run as opposed to gh pages. But it's not a bad idea, I'm om board with that and I could help move the current docs from my repo over to a directory here.

It'd require a server and a domain though. And of course the cooperation of whoever owns this repo because the built in wiki here still needs to be closed.

**Comment by chuyskywalker** [comment]
I'm pretty sure that readthedocs hosts the compiled docs.

**Comment by JonahAragon** [comment]
Oh you're correct, they have a hosted version. I only saw the installation instructions since there is a self hosted option. Ok well if we could get a guarantee from an owner of this repo that this wiki will actually be shut down this time to prevent confusion, instead of having two, we could move to it.

**Comment by AHAAAAAAA** [comment]
I was not informed of the move, else I would've prevented it from the start. I really appreciate the work you put into it, that's why I haven't touched it. However, Wikis don't need PRs. That's what makes them Wikis. This works across Wikipedia, Bulbapedia, and a thousand other sites. The community will self-police. With the fast paced nature of the repo, it's really easier to just edit the wiki directly instead of having to do PRs elsewhere. Moreover, it's confusing for it to be hosted on an alternative repo. We're not shutting this one down. I'll look into integrating something like Read the Docs, but again I'm sorry I'm not shutting this wiki down.

**Comment by chuyskywalker** [comment]
#3099
