### ISSUE TITLE
How to setup multiple accounts

### ISSUE THREAD

**Issue by deada92** [AHAAAAAAA/PokemonGo-Map#2724]
I went trought the wiki but I couldn't find how to setup multiple accounts to bypass the 1req/3sec.. Can you guys assist me?

**Comment by TFD777** [comment]
It's actually 3requests/1second.

**Comment by GibbyOH** [comment]
I was looking at doing the same thing but I am wondering if I have say 5 accounts running different scans all at -t 3 -sd 1 would it really speed up the discovery of new Pokemon. Wouldn't each account just be finding the same Pokemon?

I am looking at setting up 5 scans across different PCs and the web front end on a sixth PC with MySQL running on the web front end.

**Comment by leTokki** [comment]
You use the beehive generator in the dev branch, they have the instructions there

@GibbyOH you won't be using 5 accounts to scan a single location, but you would allocate small parts of an area to each account for them to scan, else it would be redundant.

**Comment by coffman34** [comment]
Why would you create 5 scans on different pcs? You can run them all on the same pc using the -ns command for the ones that are not the webhost.

**Comment by GibbyOH** [comment]
Because I don't want to eat up to much of the resources of one VM so I was looking at spreading the work across several VM guest that I already have up and running. My resources on the three PowerEdges I have are starting to get thin due to some other projects. 




On Sat, Jul 30, 2016 at 1:59 PM -0400, "coffman34" <notifications@github.com> wrote:












Why would you create 5 scans on different pcs? You can run them all on the same pc using the -ns command for the ones that are not the webhost.

**Comment by deada92** [comment]
https://www.jonaharagon.com/PoGoMapWiki/#!beehive.md is directed to Windows users right?

**Comment by TJohnson93** [comment]
@deada92 yes I believe so...

**Comment by deada92** [comment]
Setting multple accounts is supported with the beehive. search functionality will break though #2760 #2779
