### ISSUE TITLE
Are there any cloud servers working after mass IP ban?

### ISSUE THREAD

**Issue by TFD777** [AHAAAAAAA/PokemonGo-Map#2845]
Because at the moment I get 403 forbidden error.

**Comment by Brideau** [comment]
Seeing the same at the moment. Strangely, it was working fine until I upgraded to the new version of Pokelyzer.

 In fact, I had an older version running and logging in without an issue, while simultaneously running a newer version (2.1) with the same arguments, but it wouldn't log in.

**Comment by jforr** [comment]
When Niantic first launched the game they left the doors and windows open.  Peeking then was a grey area.  They've since shut the door and closed the windows.  They haven't put super tight locks on them (yet), but at this point you're pretty clearly breaking and entering and this entire project is now in blackhat territory.

I'd say follow pokevision's lead and respect their wishes.

**Comment by KevakaBuel** [comment]
How was this ever a grey area? Everything that gives you an advantage over everyone else that is just using the app is against Niantics ToS. It was since the beginning...

**Comment by jangrewe** [comment]
Mine is still working... ~1k visitors/day, capital city in Germany.

**Comment by chuyskywalker** [comment]
#2777
