### ISSUE TITLE
403 Forbidden Server Response

### ISSUE THREAD

**Issue by SrGMC** [AHAAAAAAA/PokemonGo-Map#2860]
## Expected Behavior

The Map (from dev branch) is deployed in IBM Bluemix, Heroku and on my PC. The program should get normal 200 responses 

## Current Behavior
Currently the program is getting a 403 forbidden response

## Possible Solution

Maybe it has something to do with the 70m change, or that my second account is banned

## Context

This happened while helping another person with an issue. It also happens to him

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7): Python 2.7 - Node.js 4.4.7
* Operating System and version (desktop or mobile): Desktop / Mac OS X 10.11.5 - Mobile / iOS 8.4 - Heroku and Bluemix

**Comment by Jankos1985** [comment]
Been having same issue since yesterday:

2016-07-31T16:25:30.824060+00:00 app[web.1]: 2016-07-31 16:25:30,823 [ search_thread][      auth_ptc] [   INFO] PTC login for: <redacted>
2016-07-31T16:25:31.390710+00:00 app[web.1]: 2016-07-31 16:25:31,390 [ search_thread][      auth_ptc] [   INFO] PTC Login successful
2016-07-31T16:25:31.578683+00:00 app[web.1]: 2016-07-31 16:25:31,578 [ search_thread][       rpc_api] [WARNING] Unexpected HTTP server response - needs 200 got 403

I've tried new PTC and google accounts as well.

**Comment by jessedobbelaere** [comment]
Same issue here, tried both PTC and google accounts.

**Comment by CtrlAltDefeat94** [comment]
Running from a VPS by any chance? Most VPS providers have been banned from accessing the API

**Comment by jessedobbelaere** [comment]
Ok yeah makes sense, running on heroku here. Just set up a docker container locally and that one runs fine 👍

**Comment by EdenGottlieb** [comment]
Same on Heroku, local works fine

**Comment by IDSninja** [comment]
same on digital ocean, and using the -ut (use tor) gives authentication timeout errors. Is there any way to specify our own SOCKS proxy?

**Comment by FrostTheFox** [comment]
CtrlAltDefeat is correct. The 403 means the IP address being used to connect to the PoGo servers is banned because it is either a cloud provider IP, or that IP has been recognized as using larger amounts of traffic than normal.
