### ISSUE TITLE
New dev version.. No Map?

### ISSUE THREAD

**Issue by stlmikey80** [AHAAAAAAA/PokemonGo-Map#2878]
Just updated.. Im not getting this.. Old version from couple days ago was working just fine

http://imgur.com/a/fHcBD

**Comment by Rikilsta** [comment]
doesn't work when I try npm install. I get the following : npm WARN deprecated minimatch@0.2.13:Please update to minimatch 3.0.2 or higher to avoid a RegExp Dos issue

**Comment by Matsu16** [comment]
Wait longer on ur npm install. it takes like 4 min.

**Comment by stlmikey80** [comment]
thanks got it works

**Comment by polyisobutylene** [comment]
cool, please close the issue

**Comment by excitedbox** [comment]
@polyisobutylene 
I did 
npm build
npm install
grunt
worked fine. Do I not need the npm build?

**Comment by polyisobutylene** [comment]
npm build isn't needed here you just need to ensure that you have the specific nodejs pre-requisites used by the project. You get those by running npm install.

It also looks like grunt build from my answer is redundant because npm install will issue the command for you.

You only need to use the grunt command if you are actively developing on the UI, it will build the current UI files and watch for changes to them and automatically rebuild for you
