### ISSUE TITLE
Can't add Pokemon to Hide/Notify in Options menu

### ISSUE THREAD

**Issue by ShadowthePast** [AHAAAAAAA/PokemonGo-Map#3071]
In the dev build, I can't add Pokemon to the Hide list or Notify list. (Also, the Map Style dropdown doesn't work.)

![](http://i.imgur.com/YkZRNqh.png)

**Comment by miaojs** [comment]
This is because the localization files didn't get created automatically. Not sure what the issue ot fix is, but you can copy the files from the static dir and rename them and move them to what the browser is looking for. Go to developer options on chrome and see which files are 404ing. Can't remember which two files it was. I think pokemon.json was one of them.

**Comment by ShadowthePast** [comment]
Looks like it's saying 
`jquery.min.js:4 GET http://localhost:5000/static/locales/pokemon.en.json 404 (NOT FOUND)`

Went ahead and copied the pokemon.en.json file from the master branch and slapped it in there, now it's working. Thanks for the help.

**Comment by Varatnar** [comment]
@ShadowthePast Simply flush the cache data for it if it happens again.
While i'm not mod or anything, don't forget to close the issue if it is not relevant anymore.
