### ISSUE TITLE
Localhost works but cannot use external IP

### ISSUE THREAD

**Issue by leej19** [AHAAAAAAA/PokemonGo-Map#3100]
Server was up and running correctly. Now cannot access from an external IP. There are no errors and I can access the map using localhost.

Anyone know what the issue may be?

**Comment by Kasmodan1** [comment]
1. First I would do a google search "what is my IP" from the servers location, wither it be your home PC or what not.
2. If that is the correct IP then I would look into the router TCP ports and make sure  you have 5000 port allowed or what ever the port you set your Port to on the run command. Default is 5000. And it should be open and pointing to your system IP. ex... 192.168.1.143 with port 5000 open in the router.

Lastly...your run command should look something like this....

python runserver.py -a ptc -u (username) -p (Password) -l "40.755591, -111.873144" -st 5 -sd 1 -t 1 **-H 0.0.0.0**

The -H command will force the .py to run off of the computers IP Address instead of localHost 127.0.0.1:5000 or localhost:5000. so when you use your external IP it should work.

**Comment by andrewda** [comment]
Already answered numerous times.
