### ISSUE TITLE
Digital Ocean - This site cannot be reached

### ISSUE THREAD

**Issue by Mokhan94** [AHAAAAAAA/PokemonGo-Map#3255]
Having an issue with Digital Ocean. I got the droplet up like it states but when I try to access the IP provided I get the error below. 
<img width="608" alt="capture" src="https://cloud.githubusercontent.com/assets/16256821/17352681/4b1454f8-58fe-11e6-8979-f51964c09eb9.PNG">

**Comment by HinoReo** [comment]
What command are you running your server with?
Try sudo'ing it.

**Comment by eppcmogen** [comment]
i dont think u specified a port, try ur ip with :5000

**Comment by turtle2472** [comment]
You will also need to make sure the port for your PoGoMap is open in the firewall, assuming you run one.

**Comment by dtandersen** [comment]
If running with docker don't forget -p 80:5000.

**Comment by Chezhiyan0808** [comment]
donot forget -H <ip> and -p <port>

**Comment by blackhattristar** [comment]
I've tried my IP with :80 and :5000 and I can't seem to get my IP to load in my browser after just setting up a droplet. Any help would be greatly appreciated. This is what I've set in my user data:

#!/bin/bash

apt-get -y update
apt-get -y install git nodejs npm python-pip nodejs-legacy python-dev
git clone -b develop https://github.com/AHAAAAAAA/PokemonGo-Map.git
cd PokemonGo-Map/
pip install -r requirements.txt
npm install
npm install -g grunt-cli
npm install node-sass
grunt build
python ./runserver.py -u myemail@gmail.com -p my password -st 10 -k mykey -l "lat, long” -H 0.0.0.0 -P 80 &

**Comment by HinoReo** [comment]
@blackhattristar 
> H 0.0.0.0
I think this is your problem, since it tells the script to run only @ localhost. Get into your droplet's page at DigitalOcean and copy your IP from there. Also, you don't need "npm install -g grunt-cli", "npm install node-sass" and "grunt build", since all of it is done within "npm install".
Also, the last line will tell you a bit of blasphemy about error 13 and/or insufficient priveleges. Sudo it.

**Comment by blackhattristar** [comment]
I'm going to post pics of the steps I'm doing and maybe someone will see where I'm going wrong. I appreciate all of your help!

![screen shot 2016-08-03 at 4 24 46 pm](https://cloud.githubusercontent.com/assets/13209070/17385482/c7f58e9e-5997-11e6-95ef-13385e733248.png)
![screen shot 2016-08-03 at 4 25 09 pm](https://cloud.githubusercontent.com/assets/13209070/17385476/c7da8e28-5997-11e6-9aac-17586ba5f3d9.png)
![screen shot 2016-08-03 at 4 25 14 pm](https://cloud.githubusercontent.com/assets/13209070/17385481/c7e28416-5997-11e6-9b76-50bdc6f82275.png)
![screen shot 2016-08-03 at 4 25 46 pm](https://cloud.githubusercontent.com/assets/13209070/17385478/c7dfae44-5997-11e6-9f51-e931b2c57ffa.png)
![screen shot 2016-08-03 at 4 28 12 pm](https://cloud.githubusercontent.com/assets/13209070/17385479/c7dfc56e-5997-11e6-889e-1a99fcdb57f0.png)
![screen shot 2016-08-03 at 4 28 45 pm](https://cloud.githubusercontent.com/assets/13209070/17385480/c7e18e80-5997-11e6-9bba-300edc691681.png)
![screen shot 2016-08-03 at 4 29 17 pm](https://cloud.githubusercontent.com/assets/13209070/17385475/c7c3d2d2-5997-11e6-8d49-de37eafd8f85.png)
![screen shot 2016-08-03 at 4 29 26 pm](https://cloud.githubusercontent.com/assets/13209070/17385477/c7df6e8e-5997-11e6-9e9c-cee0347a59db.png)

So that's kinda where I'm at.

**Comment by blackhattristar** [comment]
I finally got it to work thanks to your help. This is now what I'm seeing when I load the IP address. 

![screen shot 2016-08-03 at 5 09 22 pm](https://cloud.githubusercontent.com/assets/13209070/17386196/1c13d922-599d-11e6-8b28-3717e6c5f570.png)

Any ideas?
