### ISSUE TITLE
How to update

### ISSUE THREAD

**Issue by SirShello** [AHAAAAAAA/PokemonGo-Map#3450]
I finally got my map running, but unfortunately it doesn't work because of the presumable changes to the API. This got me thinking... From what I've read in nummerous other posts, this project is being updated very frequently and it's likely going to be updated fairly quickly after these API changes. But how do I notice that this project has been updated? And how do I update it when the update has arrived? I'm sorry if this seems like a trivial question, but I've never used github, python or any other site/application that were necessary to run this map. I put an all-nighter to get it up and running and when it finally worked but nothing showed on the map I was pretty bummed and I'm already scared of having to go through all these troubles again. Thank you very much for your answers!

**Comment by kratsg** [comment]
```git pull``` will update things for you.

**Comment by ryanzab** [comment]
@kratsg putting git pull into my script will update it?

**Comment by Andiii09** [comment]
But I need a git directory to do so, is that right? Just extracting the .zip does not with git pull.
So my question is: is this workflow correct?

```
git clone [url] -b develop
git pull origin develop
```

When I tried it first, git asked for my name and email address when I used git `pull origin develop` , is this normal? was not the case with master version.

**Comment by Alasio** [comment]
`git checkout develop
git pull`

**Comment by kratsg** [comment]
I don't know how you're grabbing it. But let's assume there's two ways:

1. You're using `git clone <repo url>`. In this case, running

  ```git pull```

  will update things for you. This is equivalent to `git pull origin master` as the default remote is called `origin` and the default branch is the current branch (usually `master`).

2. Using a tarball or zipfile. Go to where you extracted it:

  ``` cd /path/to/PokemonGo-Map```

  then run

  ```git init .```

  to set up the current directory as a local git repository. Then add

  ```git remote add origin <repo url>```

  to add the git remote, then

  ```git branch -u origin/master master```

  since the tarball/zipfile is almost always from the master branch. If it's a different branch, then you'll need to change `master` to the name of the branch you're using 

  ```git branch -u origin/<branch> <branch>```

  then go to step 1.

**Comment by xioxxio** [comment]
Thanks where do you get the git zip file from?

**Comment by freakjam** [comment]
Press on the big green button top right that says "clone or download".

**Comment by smontana** [comment]
From the main page. Try google if you can't find it.

**Comment by Andiii09** [comment]
Thanks @kratsg for the detailed explanation, cleared things up for me :)

**Comment by pet90210** [comment]
@kratsg - thank you so much!
