### ISSUE TITLE
Stops showing pokemons after time, restart fixes it.

### ISSUE THREAD

**Issue by CarlSchou** [AHAAAAAAA/PokemonGo-Map#356]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discordapp.com/invite/qbpVH6b).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:
Windows 10 and Windows Server R2

Installed version of Python:
2.7.10

### Steps to reproduce
1. Start
2. Let it run?
3. Done

### What have you tried?
1. Restarting (Which fixes it)
2. Updating

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).
`Completed: 85.0%
[-] looping: step 86 of 100
[+] Searching for Pokémon at location 55.5611377 12.0237975
Completed: 86.0%
[-] looping: step 87 of 100
[+] Searching for Pokémon at location 55.5611377 12.0262975
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
Completed: 87.0%
[-] looping: step 88 of 100
[+] Searching for Pokémon at location 55.5611377 12.0287975
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
Completed: 88.0%
[-] looping: step 89 of 100
[+] Searching for Pokémon at location 55.5611377 12.0312975
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying`

**Comment by Darkrift411** [comment]
Ive had this happen in all builds over the last 5+ hours. And no, it happens when servers are up. Restarting fixes it and I have had it happen to one while another (I am running 6 of these) continues to work just fine. It almost always happens for me at one of the 2 points:

[-] register_background_thread called
[-] register_background_thread: queueing

or right after it completes teh purging of stale pokemon. This is split between 4 different servers. One is Mint 17, the others are all cent 6.8 - Each time I just ctrl+c and start it back.

Also this was just clsoed as "servers are down", but I have 6 of these working right now and none of them have stopped in the last 15 minutes.
