### ISSUE TITLE
long lasting

### ISSUE THREAD

**Issue by madjapahit** [AHAAAAAAA/PokemonGo-Map#437]
with the same google id and ptc secret, this will be long lasting to hold?

**Comment by madjapahit** [comment]
you can find google id and ptc secret configuration on credentials.json

**Comment by medghaim** [comment]
The googleid is the Google Maps API key, found as `gmaps_key` under `credentials.json`. We've already ran into issues with the rate limit being hit for that API key, so the smart play would be to make your own google maps API key which you can do [here.](https://developers.google.com/maps/faq). Then you could add `credentials.json` to your `.gitignore` file - but be warned, you'll have to keep your eye out and check if credentials.json is ever changed, since it's on your `.gitignore`.

As for the PTC secret, not 100% where that came from, or if you can even apply for one - it may have been reverse engineered? I dunno. Someone who knows more about that could answer!

**Comment by madjapahit** [comment]
@medghaim thanks ! yeah we ran out for our self-generate gmap api too, and offered to extend by billing system.

but i curious with usage of android-id and ptc_client_secret, if there's another way to generate ptc_client_secret i would like to know too!
