### ISSUE TITLE
Only pokemon from last search loop visible

### ISSUE THREAD

**Issue by Zsub** [AHAAAAAAA/PokemonGo-Map#741]
On development, both the map and /pokemon only contain those pokemon the app found during the latest search, instead of all valid pokemon that haven't yet despawned.

Reproduce:
 1. run latest dev
 1. let it run a while
 1. F5, see lots of pokemon on the map
 1. wait for auto refresh
 1. lots of pokemons are gone 😕 (only those from latest update are shown)

**Comment by Bakies** [comment]
I could reproduce this, I had a ratatta at my house with 12m left on it and after the second 100% in the log the rattata vanished after a web page refresh

**Comment by Bakies** [comment]
Discord user Domin0e#6753 made a video demonstration of this bug
https://www.youtube.com/watch?v=PzIziKz7L38

**Comment by jamesinc** [comment]
Copying my comment from #746:

Hey, I've had this issue too and have been looking at it, it is a timezone bug. A quick workaround is to remove the timezone calculation logic from the map.js, so you end up with:

```js
    $.each(markers, function(i, item){
        if (item.disapear <= lastStamp)
            item.m.setMap(null);        
    });
```

I *think* the root cause is in `models.py`, where detect_time (line 125) is being stored as a local time, whereas other times are UTC.

**Edit: just to be clear, this is on the develop branch.**

**Comment by coldasicet** [comment]
after tried your fix it works

**Comment by Zsub** [comment]
That `map.js` edit works around it indeed. Probably have to see if Pokemon still disappear properly.

**Comment by coldasicet** [comment]
just checked it dissapeared but seems like they added some things so time to update the git :P

**Comment by jamesinc** [comment]
@coldasicet the latest pull didn't resolve it. I'll see if I can work out the actual issue

**Comment by coldasicet** [comment]
ah ic, my bad jumping to conclusions ^^

**Comment by jamesinc** [comment]
@coldasicet actually I worked it out, I'm pretty sure. I overlooked the root issue initially. In JavaScript, `dObj.getTime()` always returns the milliseconds since Jan 1 1970 **UTC**. So they're applying a timezone offset math to it when they shouldn't be. So my fix of removing the timezone offset logic to workaround the issue is, actually, I think, the correct solution to the bug.

**Comment by Zsub** [comment]
now trying with `datetime.utcnow()`

**Comment by coldasicet** [comment]
well i just downloaded it, and its still there but the new -L i dont how to use ;(

**Comment by shadow7412** [comment]
@jamesinc's fix worked for me as well.

**Comment by lhickin** [comment]
Thanks @jamesinc, worked perfectly

**Comment by Lpk44** [comment]
I tried the fix from @jamesinc but the problem still persists for me.

**Comment by shadow7412** [comment]
It would have been cached javascript I'll bet.

**Comment by Bakies** [comment]
@jamesinc make a pull request with your fix and link this thread

**Comment by Bakies** [comment]
@DerScreever is this fixed? it shouldnt be closed if this is still an issue

**Comment by jamesinc** [comment]
@Bakies I just did a fresh pull of the develop branch this morning and they've rewritten big chunks of map.js, and included this fix along the way.
