### ISSUE TITLE
Pokemon Showing up And dissapering Right after

### ISSUE THREAD

**Issue by coldasicet** [AHAAAAAAA/PokemonGo-Map#746]
### Environment info
Operating System:
Windows 
Installed version of Python:
2,7

### Steps to reproduce
1. Download this
2.Run

### What have you tried?
1. Run this

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

how"?

**Comment by medghaim** [comment]
Could you please provide a little clarification? Are you on the `master` or `develop` branch? What command/args did you use to run it?

**Comment by coldasicet** [comment]
Develop

**Comment by coldasicet** [comment]
After running runserver.py

**Comment by JZ6** [comment]
god damn

**Comment by coldasicet** [comment]
?

**Comment by coldasicet** [comment]
did i download the wrong one?

**Comment by jamesinc** [comment]
Hey, I've had this issue too and have been looking at it, it is a timezone bug. A quick workaround is to remove the timezone calculation logic from the map.js, so you end up with:

```js
    $.each(markers, function(i, item){
        if (item.disapear <= lastStamp)
            item.m.setMap(null);        
    });
```

I *think* the root cause is in `models.py`, where detect_time (line 125) is being stored as a local time, whereas other times are UTC.

**Comment by Bakies** [comment]
possibly the same issue as #741

**Comment by coldasicet** [comment]
wehn i look it might be the same

**Comment by JZ6** [comment]
@jamesinc  thx for the fix we already have it in  apr
