### ISSUE TITLE
Failed building wheel for Markypsafe

### ISSUE THREAD

**Issue by Kevinclon** [AHAAAAAAA/PokemonGo-Map#838]
https://gyazo.com/5c45d0f70457ec252c5bf362b6b500aa

**Comment by zyxer** [comment]
"do pip install setuptools==21.2.1 and try again
some other options might be available if that does not work"

https://github.com/AHAAAAAAA/PokemonGo-Map/issues/466

**Comment by Kevinclon** [comment]
Well it got me farther, but now i get hung up here

https://gyazo.com/2370185bb8160aa40815be3d6258d9b2

**Comment by Kant73** [comment]
Find this on Stackoverflow ;)
I had this problem yesterday. I resolved it by downloading the MarkupSafe wheel and installing with pip. The problem was way over my head. Something about compiler flags in order to suppress an error when generating the Speedups file, I think.

1) Download the wheel from this link: http://www.lfd.uci.edu/~gohlke/pythonlibs/#markupsafe.

2) On Windows, open a command window in the same directory as the wheel.

3) run "pip install DOWNLOADED_WHEEL_FILE.whl."

Solve my problem ;)
