### ISSUE TITLE
Advice on speeding up getting pokemons?

### ISSUE THREAD

**Issue by PokeDon** [AHAAAAAAA/PokemonGo-Map#884]
![capture](https://cloud.githubusercontent.com/assets/20577279/17026874/8a2913d0-4f59-11e6-8f08-014075334b22.JPG)

It takes forever..

Any advice on speeding this up..? 

**Arguments:** python runserver.py -a google -u XXX@gmail.com -p XXX -l "LOCATION" -st 100

**Comment by tj1627** [comment]
drop your steps way down.  Whatever you enter as the -st value, it'll take x^2 steps to complete.  Rough math puts each step at around 1 second.  If you were to step down and run, say, 10 steps, instead of 100, you'll complete in under 2 minutes.  Right now you won't complete for almost 3 hours.

For reference, 10 steps covers about 8 square miles for me

**Comment by Kant73** [comment]
-st 100 ? You want to map a really huge are with that parameter. I don't think that you need more than -st 10 if it's for playing, but maybe you want to do another thing ;)
Anyway, there is already a pull request for a new algorithm for filling the map (30% faster approximately)

**Comment by skeldoor** [comment]
100 steps is MASSIVE

**Comment by CarlTaylor1989** [comment]
Yep you do not need 100 steps, 10 steps is a good radius. Closing.
