### ISSUE TITLE
Searching is slow...parallelize?

### ISSUE THREAD

**Issue by rsearles35** [AHAAAAAAA/PokemonGo-Map#923]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discord.gg/Kzp4yky).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:
Mac OS X

Installed version of Python:
2.7.12

### Feature Request
The searching seems to be very slow. I am not sure how much of this is tied to sending/receiving requests from the Pokemon Go server, but I figured I'd suggest checking out the python multiprocessing library (specifically, creating a process pool and using it to call a map over the search function) in order to parallelize the search step. I noticed that searching takes a while, but my CPU isn't being taxed. This seems like an embarrassingly parallel problem, so I figured I'd make a suggestion :)

**Comment by CarlTaylor1989** [comment]
How many steps did you put in the param?

**Comment by billbo99** [comment]
My guess in order to avoid flagging the account, the account has to move in a realistic manner.  The only way to parallelize things would be to have each thread running as a different user.

**Comment by trippyhat** [comment]
@CarlTaylor1989 Yes, if OP put the steps as too high, then the map won't get refreshed as fast, making it appear as though the  map isn't updating.

However, OP's suggestion is pretty nice too. Making the search multi-threaded may cover more ground in less time, allowing us to get a bigger picture while still having acceptable refresh time.

Making it multi-threaded may be tricky, in terms of trying to appear as human though.

That is, if each thread is processing a different location and you use your single user account, each thread will be making requests to the pokemon go servers and then you'll appear as teleporting around the map at random. Not very human-like.

Suggestions: 
  - Perhaps maybe specify one user account per thread, and make each thread cover a specific radius so that they don't overlap with other threads? ie, thread 1 covers a radius of .5 km using user A, thread 2 covers from .5 km to 1km using user B, etc...

**Comment by vincesmits** [comment]
The latest version is able to grind my i7 to a halt after scanning for a longer period of time
