### ISSUE TITLE
Synology DS213j & pycryptodomex incompatibility

### ISSUE THREAD

**Issue by rlyons20** [AHAAAAAAA/PokemonGo-Map#945]
It looks like the pycryptodomex module doesn't like the CPU in the Synology DS213j.  FYI, it is a marvell armada 370 88f6707.

The package starts to install, but then gives an error, and fails. I've pasted the error at the bottom.

Any ideas for how to get it to install?  Any chance we could redesign the script to use a package with wider compatibility??

Thanks, all!

### Environment info
Operating System:
Synology DSM 6.0.1
Installed version of Python:
2.7

### Steps to reproduce
1. run requirements script
2.
3.

### What have you tried?
1. manual install of pycryptodomex

### Logs or other output that would be helpful
warning: no support for Intel AESNI instructions
unable to execute '/usr/local/arm-unknown-linux-gnueabi/bin/arm-unknown-linux-gnueabi-ccache-gcc': No such file or directory

**Comment by jaydlawrence** [comment]
Hi @rlyons20.
This seems to be a problem with the pycryptodomex package.

I have come onto a similar issue trying to install PokemonGo-Map on my HP home server.

Since you already have all of the information for debugging, could you please raise the bug on the pycryptodomex repo?
https://github.com/Legrandin/pycryptodome/issues

Cheers

**Comment by rlyons20** [comment]
I actually just sidestepped the problem completely by installing Ubuntu on and old Intel NUC I had laying around.

It's all good now :)
