### ISSUE TITLE
id parameter

### ISSUE THREAD

**Issue by iamdevice** [AHAAAAAAA/PokemonGo-Map#985]
please add ID parameter
I would like get some maps for different coords
For example:
I run 1 process like example.py id=123 and run second process example.py id=234 and want to see maps on http://127.0.0.1:5000/id123 and http://127.0.0.1:5000/id234

**Comment by welshboy** [comment]
If you want two instanced then use the -p flag and set one to -p 5000 and the other to -p 5001 ?
You'll probably want to use two separate accounts as well, if searching multiple locations

**Comment by iamdevice** [comment]
But if I want to make 10-100 requests I can't use it
Just I write telegram bot for send map screenshots

**Comment by Tigershark2005** [comment]
I'm looking into this, it would have to include a process spawn with that identifier and the browser would GET the identifier, as POST wouldn't make it as friendly. I may start that tonight as I've been thinking the same thing. My issue with changing ports is that I would have to port worward a ton instead of just one. @DerScreever could you comment on the reason for close?
